server:
  port: 1205
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost"
    username: "root"
    password: "Rashmi@165"
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true